### ISSUE TITLE
Install of checksumthing doesn't work

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/checksumthing#6]
I cloned the repo and then ran `python setup.py install`. Then I tried to run `checksumthing -h`. The script crashed and I got this message:

```
Traceback (most recent call last):
  File "/usr/local/bin/checksumthing", line 9, in <module>
    load_entry_point('Checksumthing==0.0.1', 'console_scripts', 'checksumthing')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/checksumthing.py", line 4, in <module>
    __import__('pkg_resources').run_script('Checksumthing==0.0.1', 'checksumthing.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/Checksumthing-0.0.1-py2.7.egg/EGG-INFO/scripts/checksumthing.py", line 7, in <module>
    from Checksumthing import manifest_formats
ImportError: cannot import name manifest_formats
```

**Comment by henryborchers** [comment]
should work now. PULL! PULL! PULL
